# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['./'],
             binaries=[],
             datas=[
                ('./sudoku/gui/assets/0.png', './sudoku/gui/assets/'),
                ('./sudoku/gui/assets/initial.png', './sudoku/gui/assets/'),
                ('./sudoku/gui/assets/waiting.png', './sudoku/gui/assets/'),
                ('./sudoku/gui/assets/6.png', './sudoku/gui/assets/'),
                ('./sudoku/gui/assets/4.png', './sudoku/gui/assets/'),
                ('./sudoku/gui/assets/waiting_panel.png', './sudoku/gui/assets/'),
                ('./sudoku/gui/assets/playing_panel.png', './sudoku/gui/assets/'),
                ('./sudoku/gui/assets/8.png', './sudoku/gui/assets/'),
                ('./sudoku/gui/assets/1.png', './sudoku/gui/assets/'),
                ('./sudoku/gui/assets/youwin_panel.png', './sudoku/gui/assets/'),
                ('./sudoku/gui/assets/9.png', './sudoku/gui/assets/'),
                ('./sudoku/gui/assets/3.png', './sudoku/gui/assets/'),
                ('./sudoku/gui/assets/5.png', './sudoku/gui/assets/'),
                ('./sudoku/gui/assets/7.png', './sudoku/gui/assets/'),
                ('./sudoku/gui/assets/current.png', './sudoku/gui/assets/'),
                ('./sudoku/gui/assets/violation.png', './sudoku/gui/assets/'),
                ('./sudoku/gui/assets/2.png', './sudoku/gui/assets/'),
                ('./sudoku/gui/assets/block.png', './sudoku/gui/assets/'),
             ],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='main',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='main')
